// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCNDqe2tgXfiyIc2kO9A57LDzpxFTS8B8',
    appId: '1:797081880414:web:b51088fbabe497049931cf',
    messagingSenderId: '797081880414',
    projectId: 'daily-coder',
    authDomain: 'daily-coder.firebaseapp.com',
    storageBucket: 'daily-coder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlVYa0NlaoYacyN-jHninEaxrARkRTDU8',
    appId: '1:797081880414:android:dc61539b4562f5579931cf',
    messagingSenderId: '797081880414',
    projectId: 'daily-coder',
    storageBucket: 'daily-coder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfvq7OFIGWo5K9KDrjtRY1MwYc75xB1Y0',
    appId: '1:797081880414:ios:f14350861a4cd7b29931cf',
    messagingSenderId: '797081880414',
    projectId: 'daily-coder',
    storageBucket: 'daily-coder.appspot.com',
    iosClientId: '797081880414-9c74mjr0shs6pgeo4t9v8us8jjn7h52t.apps.googleusercontent.com',
    iosBundleId: 'com.cheemscoder.dailyCoders',
  );
}
